### ISSUE TITLE
Haddocks don't build due to generic-trie 

### ISSUE THREAD

**Issue by ocramz** [ocramz/heidi#17]
GT has a too restrictive bound on base : https://github.com/glguy/tries/issues/19

**Comment by ocramz** [comment]
Closed with #19 #18

**Comment by treeowl** [comment]
I'm about to release a version of `generic-trie` that builds (without warnings, even) on GHC 9.4. You may wish to unincorporate.

**Comment by ocramz** [comment]
good catch! thank you @treeowl

**Comment by treeowl** [comment]
And it's released!
